### ISSUE TITLE
Remove "Subset Standards" section?

### ISSUE THREAD

**Issue by masinter** [mrbhardy/pdfmime#10]
there is already a paragraph in the Intro.

It should be said that you use application/pdf for all of the subsets, and also explain PDF/A1 vs. PDF/A3.

The text in PDFMIME might be reusable.

**Comment by mrbhardy** [comment]
The subsets could have a healthy, but succinct, set of descriptions that is far more than would be appropriate in the introduction.  I also don't know why we'd focus on PDF/A1 vs. PDF/A3 for PDFMIME...

**Comment by masinter** [comment]
check pdfmime doc section 2 for text and referencese

**Comment by masinter** [comment]
i reorganized as noted b the overview and history still need work

**Comment by masinter** [comment]
the section was rewritten
