### ISSUE TITLE
clarification of coordinates for fragments

### ISSUE THREAD

**Issue by masinter** [mrbhardy/pdfmime#12]
(from Alexey)

What is "the default user space coordinate system"?
(Are coordinate values in fragments measured in what?)

**Comment by mrbhardy** [comment]
The default user space is defined in PDF and is a device independent space.  The default user space is 1/72 inch per unit.  See section 8.3.2.3 "User space" in PDF.

**Comment by masinter** [comment]
added (see <xref target='ISOPDF'/> section  8.3.2.3 "User Space")

not sure whether it should explain more inline

**Comment by masinter** [comment]
defined it here & gave reference to section in ISOPDF
