### ISSUE TITLE
more undefined terms XObject JavaScript

### ISSUE THREAD

**Issue by masinter** [mrbhardy/pdfmime#14]
(from Alexey)
Does mentioning of JavaScript and XObject need Informative References?

**Comment by mrbhardy** [comment]
Let's get the simple one out of the way.  XObject is a PDF concept, so it doesn't need a reference, other than to the PDF specification (we could call out the chapter that XObject is defined).

JavaScript could be pointed out, but it is also normatively referenced from the ISO specification.  We have been creating ECMAScript standards for PDF, so they could be referenced...

**Comment by masinter** [comment]
This is in the "security considerations" section. My temptation is to just remove the XObject reference and leave JavaScript without a reference.

```
           These scripts are
            expressed in a version of JavaScript and are intended
            for execution by the PDF processor.
```
