### ISSUE TITLE
be consistent about "" and ''

### ISSUE THREAD

**Issue by masinter** [mrbhardy/pdfmime#3]
quotes are used inconsistently. the current file also has some windows ``  left and right quotes.
sometimes used to mark keywords and parameters in running text. 

I think there's some new xml2rfc markup that could be used.

**Comment by mrbhardy** [comment]
I suspect this came in with copy/paste from other documents.  I don't see the need for discussion and we should just fix.

**Comment by masinter** [comment]
fixed, add <spanx  style="verb"> around when quotes were around keywords
