### ISSUE TITLE
PDF/1.0 reference in Introduction

### ISSUE THREAD

**Issue by masinter** [mrbhardy/pdfmime#6]
The first version of PDF, 1.0, was published in 1993 by Adobe Systems [REF needed]. 

this is just background. Maybe just omit it

**Comment by mrbhardy** [comment]
It may be worth mentioning that it has been around since 1993 as a published standard, just to give a sense of history.  Is there a way to do this without a reference?

**Comment by masinter** [comment]
I think references are important if you have to go read the document. But here we're just reporting a historical fact.
