### ISSUE TITLE
section 2 History

### ISSUE THREAD

**Issue by masinter** [mrbhardy/pdfmime#8]
What's there is overlapping with the Introduction. I'd suggest merging.

In addition, I think we might copy some of the text from pdfrfc:

 For most of the common platforms in use (iOS, OS X, Windows, Android, ChromeOS, Kindle) and for most browsers (Edge, Safari, Chrome, Firefox), PDF viewing is built in. In addition there are many PDF viewers available for download and install.

**Comment by mrbhardy** [comment]
I think history was intended to be a little deeper than the introduction.  An alternative would be to leave the introduction without too much history and go more complete here...

**Comment by masinter** [comment]
reorganized Introduction and History to make section content match
